"""Public package exports for python-duco-connectivity."""

from importlib.metadata import PackageNotFoundError, version

from .client import DucoClient
from .exceptions import (
    DucoConnectionError,
    DucoError,
    DucoRateLimitError,
    DucoWriteLimitError,
)
from .models import (
    Action,
    ActionItem,
    ActionItemList,
    ActionNode,
    ActionResult,
    ActionResultStatus,
    ActionValueType,
    ApiEndpoint,
    ApiEndpointInfo,
    ApiInfo,
    BoardInfo,
    Config,
    ConfigGroup,
    ConfigGroupStruct,
    ConfigNode,
    ConfigNodeOverview,
    ConfigNodeStruct,
    ConfigSection,
    ConfigValue,
    ConfigValueOptions,
    ConfigValueString,
    ConfigZone,
    ConfigZonesOverview,
    ConfigZoneStruct,
    DiagComponent,
    DiagStatus,
    InfoGroup,
    InfoGroupStruct,
    InfoZone,
    InfoZonesOverview,
    InfoZoneStruct,
    LanInfo,
    NetworkType,
    Node,
    NodeActionItemList,
    NodeGeneralInfo,
    NodeListActionItemList,
    NodeMotorStateInfo,
    NodeOverview,
    NodeSensorInfo,
    NodeType,
    NodeVentilationInfo,
    PatchConfigNodeValue,
    PatchConfigValue,
    VentilationMode,
    VentilationState,
)

try:
    __version__ = version("python-duco-connectivity")
except PackageNotFoundError:
    __version__ = "0.0.0"

__all__ = [
    "Action",
    "ActionItem",
    "ActionItemList",
    "ActionNode",
    "ActionResult",
    "ActionResultStatus",
    "ActionValueType",
    "ApiEndpoint",
    "ApiEndpointInfo",
    "ApiInfo",
    "BoardInfo",
    "Config",
    "ConfigGroup",
    "ConfigGroupStruct",
    "ConfigNode",
    "ConfigNodeOverview",
    "ConfigNodeStruct",
    "ConfigSection",
    "ConfigZone",
    "ConfigZonesOverview",
    "ConfigZoneStruct",
    "ConfigValue",
    "ConfigValueOptions",
    "ConfigValueString",
    "DucoClient",
    "DucoConnectionError",
    "DucoError",
    "DucoRateLimitError",
    "DucoWriteLimitError",
    "DiagComponent",
    "DiagStatus",
    "InfoGroup",
    "InfoGroupStruct",
    "InfoZone",
    "InfoZonesOverview",
    "InfoZoneStruct",
    "LanInfo",
    "NetworkType",
    "Node",
    "NodeActionItemList",
    "NodeGeneralInfo",
    "NodeListActionItemList",
    "NodeMotorStateInfo",
    "NodeOverview",
    "NodeSensorInfo",
    "NodeType",
    "NodeVentilationInfo",
    "PatchConfigNodeValue",
    "PatchConfigValue",
    "VentilationMode",
    "VentilationState",
    "__version__",
]
